version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/apache-nas"
    schedule:
      interval: monthly
  - package-ecosystem: "docker"
    directory: "/sftp-server"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/geoserver-datadir-sync"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/geoserver-lb-geoserver-sync"
    schedule:
      interval: "monthly"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "monthly"
